server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lottery?useSSL=false&serverTimezone=UTC
    username: root
    password: Manish@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  application:
    name: lottery-system

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
